INSERT INTO CH13.CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES ('Lala', 'La', '1980-07-30');
INSERT INTO CH13.CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES ('Lili', 'Li', '1990-11-02');
INSERT INTO CH13.CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES ('Lolo', 'Lo', '1964-02-28');

INSERT INTO CH13.CONTACT_TEL_DETAIL (CONTACT_ID, TEL_TYPE, TEL_NUMBER) VALUES (1, 'MOBILE', '1234567890');
INSERT INTO CH13.CONTACT_TEL_DETAIL (CONTACT_ID, TEL_TYPE, TEL_NUMBER) VALUES (1, 'HOME', '1234567890');
INSERT INTO CH13.CONTACT_TEL_DETAIL (CONTACT_ID, TEL_TYPE, TEL_NUMBER) VALUES (2, 'HOME', '1234567890');

INSERT INTO CH13.CONTACT_INTEREST (CONTACT_ID, INTEREST_TYPE, INTEREST_NUMBER) VALUES (1, 'TYPE1', '1234567890');
INSERT INTO CH13.CONTACT_INTEREST (CONTACT_ID, INTEREST_TYPE, INTEREST_NUMBER) VALUES (1, 'TYPE2', '1234567890');
INSERT INTO CH13.CONTACT_INTEREST (CONTACT_ID, INTEREST_TYPE, INTEREST_NUMBER) VALUES (2, 'TYPE1', '1234567890');


INSERT INTO CH13.HOBBY (HOBBY_ID) VALUES ('SWIMMING');
INSERT INTO CH13.HOBBY (HOBBY_ID) VALUES ('JOGGING');
INSERT INTO CH13.HOBBY (HOBBY_ID) VALUES ('PROGRAMMING');
INSERT INTO CH13.HOBBY (HOBBY_ID) VALUES ('MOVIES');
INSERT INTO CH13.HOBBY (HOBBY_ID) VALUES ('READING');

INSERT INTO CH13.CONTACT_HOBBY_DETAIL(CONTACT_ID, HOBBY_ID) VALUES (1, 'SWIMMING');
INSERT INTO CH13.CONTACT_HOBBY_DETAIL(CONTACT_ID, HOBBY_ID) VALUES (1, 'MOVIES');
INSERT INTO CH13.CONTACT_HOBBY_DETAIL(CONTACT_ID, HOBBY_ID) VALUES (2, 'SWIMMING');